(function(){
"use strict";
const BOOKING_KEY="bookings", CLIENT_KEY="professionalStudio.clients", GALLERY_KEY="professionalStudioGalleries";
let bookings=[], clients=[], selectedId=null;
const $=id=>document.getElementById(id);
function read(key,fallback){try{const x=localStorage.getItem(key);return x?JSON.parse(x):fallback}catch{return fallback}}
function save(){try{localStorage.setItem(CLIENT_KEY,JSON.stringify(clients));return true}catch{return false}}
function id(){return "client-"+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function money(n){return "₹"+Number(n||0).toLocaleString("en-IN")}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
function normalize(c){return {id:c.id||id(),name:String(c.name||"Unnamed client").trim(),email:String(c.email||"").trim(),phone:String(c.phone||"").trim(),notes:String(c.notes||""),createdAt:c.createdAt||new Date().toISOString(),updatedAt:c.updatedAt||c.createdAt||new Date().toISOString()}}
function bookingClient(b){return {name:b.fullName||b.clientName||b.name||"Unnamed client",email:b.email||b.clientEmail||"",phone:b.phone||b.clientPhone||""}}
function syncFromBookings(){const map=new Map(clients.map(c=>[String(c.email||"").toLowerCase(),c]));bookings.forEach(b=>{const x=bookingClient(b),key=x.email.toLowerCase();if(!x.name||x.name==="Unnamed client")return;let c=key?map.get(key):null;if(!c){c=normalize({id:id(),...x});clients.push(c);if(key)map.set(key,c)}else{if(!c.phone&&x.phone)c.phone=x.phone;if(!c.email&&x.email)c.email=x.email}});save()}
function syncFromGalleries(){const galleries=read(GALLERY_KEY,[]);if(!Array.isArray(galleries))return;const map=new Map(clients.map(c=>[String(c.email||c.name||"").toLowerCase(),c]));galleries.forEach(g=>{const name=String(g.clientName||g.client||"").trim();if(!name)return;const key=name.toLowerCase();if(!map.has(key)){const c=normalize({id:id(),name});clients.push(c);map.set(key,c)}});save()}
function getBookings(c){return bookings.filter(b=>{const x=bookingClient(b);return (c.email&&x.email&&x.email.toLowerCase()===c.email.toLowerCase())||(c.phone&&x.phone&&x.phone===c.phone)||(c.name&&x.name&&x.name.toLowerCase()===c.name.toLowerCase())})}
function getGalleries(c){const galleries=read(GALLERY_KEY,[]);if(!Array.isArray(galleries))return [];return galleries.filter(g=>{const n=String(g.clientName||g.client||"").trim().toLowerCase();return n&&c.name&&n===c.name.toLowerCase()})}
function render(){const q=($("clientSearch").value||"").toLowerCase().trim(),filter=$("clientFilter").value;let list=clients.filter(c=>{const bs=getBookings(c);const match=!q||[c.name,c.email,c.phone].join(" ").toLowerCase().includes(q);const active=bs.some(b=>!['completed','cancelled','rejected'].includes(String(b.status||b.bookingStatus||"").toLowerCase()));const complete=bs.some(b=>String(b.status||b.bookingStatus||"").toLowerCase()==="completed");return match&&(filter==="all"||(filter==="active"&&active)||(filter==="completed"&&complete))});$("clientList").innerHTML=list.map(c=>{const bs=getBookings(c),active=bs.filter(b=>!['completed','cancelled','rejected'].includes(String(b.status||b.bookingStatus||"").toLowerCase())).length;return `<button class="client-row ${c.id===selectedId?'active':''}" data-client="${esc(c.id)}"><div><div class="client-name">${esc(c.name)}</div><div class="client-meta"><span>${esc(c.email||"No email")}</span><span>${esc(c.phone||"No phone")}</span></div></div><span class="client-badge">${active} active</span></button>`}).join("");$("clientEmpty").hidden=list.length!==0;$("clientList").querySelectorAll("[data-client]").forEach(b=>b.addEventListener("click",()=>{selectedId=b.dataset.client;render();renderDetail()}));renderStats();}
function renderStats(){let active=0,complete=0,revenue=0;bookings.forEach(b=>{const s=String(b.status||b.bookingStatus||"").toLowerCase();if(!['completed','cancelled','rejected'].includes(s))active++;if(s==="completed")complete++;revenue+=Number(b.packagePrice||b.price||b.total||0)||0});$("totalClients").textContent=clients.length;$("activeClientBookings").textContent=active;$("completedClientBookings").textContent=complete;$("clientRevenue").textContent=money(revenue)}
function renderDetail(){const c=clients.find(x=>x.id===selectedId);if(!c){$("clientDetail").innerHTML='<div class="detail-empty"><span>◎</span><h2>Select a client</h2><p>Choose a client to view contact details, booking history and notes.</p></div>';return}const bs=getBookings(c).sort((a,b)=>new Date(b.createdAt||b.date||0)-new Date(a.createdAt||a.date||0));$("clientDetail").innerHTML=`<div class="detail-header"><div><h2>${esc(c.name)}</h2><p>${esc(c.email||"No email")} ${c.phone?' · '+esc(c.phone):''}</p></div><button class="secondary" id="editClient" type="button">Edit</button></div><div class="detail-section"><h3>Booking history</h3>${bs.length?bs.map(b=>`<div class="booking-item"><strong>${esc(b.serviceName||b.service||"Photography session")}</strong><span>${esc(b.eventDate||b.date||"Date not set")} · ${esc(b.status||b.bookingStatus||"Pending")} · ${money(b.packagePrice||b.price||b.total||0)}</span></div>`).join(""):'<p class="notes">No bookings recorded for this client yet.</p>'}</div><div class="detail-section"><h3>Galleries</h3>${getGalleries(c).length?getGalleries(c).map(g=>`<div class="booking-item"><strong>${esc(g.name||g.galleryName||"Client gallery")}</strong><span><a href="clientgallery.html">Manage gallery</a></span></div>`).join(""):'<p class="notes">No galleries linked to this client yet.</p>'}</div><div class="detail-section"><h3>Notes</h3><p class="notes">${esc(c.notes||"No notes yet.")}</p></div><div class="detail-actions"><button class="secondary" id="deleteClient" type="button">Delete client</button></div>`;$("editClient").onclick=()=>openModal(c);$("deleteClient").onclick=()=>{if(confirm("Delete this client record? Booking history will remain unchanged.")){clients=clients.filter(x=>x.id!==c.id);selectedId=null;save();render();renderDetail();window.PS&&PS.toast("Client removed","success")}}}
function openModal(c){$("clientModal").hidden=false;$("clientModalTitle").textContent=c?"Edit client":"Add client";$("clientName").value=c?.name||"";$("clientEmail").value=c?.email||"";$("clientPhone").value=c?.phone||"";$("clientNotes").value=c?.notes||"";$("clientForm").dataset.id=c?.id||"";setTimeout(()=>$("clientName").focus(),0)}
function closeModal(){$("clientModal").hidden=true;$("clientForm").reset();delete $("clientForm").dataset.id}
function init(){bookings=Array.isArray(read(BOOKING_KEY,[]))?read(BOOKING_KEY,[]):[];clients=Array.isArray(read(CLIENT_KEY,[]))?read(CLIENT_KEY,[]).map(normalize):[];syncFromBookings();syncFromGalleries();const params=new URLSearchParams(location.search);const target=(params.get("email")||params.get("phone")||params.get("name")||"").trim().toLowerCase();if(target){const found=clients.find(c=>(c.email||"").toLowerCase()===target||(c.phone||"").toLowerCase()===target||(c.name||"").toLowerCase()===target);if(found)selectedId=found.id;}render();$("clientSearch").addEventListener("input",render);$("clientFilter").addEventListener("change",render);$("addClientBtn").onclick=()=>openModal();$("emptyAddClient").onclick=()=>openModal();$("closeClientModal").onclick=closeModal;$("cancelClient").onclick=closeModal;$("clientModal").addEventListener("click",e=>{if(e.target===$("clientModal"))closeModal()});$("clientForm").addEventListener("submit",e=>{e.preventDefault();const data=normalize({id:$("clientForm").dataset.id||id(),name:$("clientName").value,email:$("clientEmail").value,phone:$("clientPhone").value,notes:$("clientNotes").value,createdAt:new Date().toISOString()});const i=clients.findIndex(c=>c.id===data.id);if(i>=0)clients[i]={...clients[i],...data,updatedAt:new Date().toISOString()};else clients.unshift(data);save();selectedId=data.id;closeModal();render();renderDetail();window.PS&&PS.toast("Client saved","success")});window.addEventListener("storage",e=>{if([BOOKING_KEY,CLIENT_KEY,GALLERY_KEY].includes(e.key)){bookings=read(BOOKING_KEY,[]);clients=read(CLIENT_KEY,[]).map(normalize);syncFromBookings();syncFromGalleries();render();renderDetail()}})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();
